/** API base URL: runtime /config.json overrides Vite env (local dev). */

const buildTimeBase = (import.meta.env.VITE_TENANT_API_URL ?? '').replace(/\/$/, '');

let apiBase = buildTimeBase;

function normalizeBase(url: string): string {
  return url.trim().replace(/\/$/, '');
}

/** Load `/config.json` generated by container entrypoint at startup. */
export async function initApiBaseUrl(): Promise<void> {
  try {
    const response = await fetch('/config.json', { cache: 'no-store' });
    if (!response.ok) {
      return;
    }
    const data = (await response.json()) as { apiUrl?: string };
    if (data.apiUrl?.trim()) {
      apiBase = normalizeBase(data.apiUrl);
    }
  } catch {
    // Local Vite dev: no config.json; keep build-time / .env value.
  }
}

export function getApiBaseUrl(): string {
  return apiBase;
}
